// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGXqqOyNrOpKnegR86hxGZ9AlzqgPUGek',
    appId: '1:379436412071:web:3431e513f2815a2a70ff82',
    messagingSenderId: '379436412071',
    projectId: 'ridepair-466010',
    authDomain: 'ridepair-466010.firebaseapp.com',
    storageBucket: 'ridepair-466010.firebasestorage.app',
    measurementId: 'G-EWJVM0CXKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDovYTU4dEPZnzZXrDAVj30UEwuJhSkO1s',
    appId: '1:379436412071:android:2feb67cafaf2d50770ff82',
    messagingSenderId: '379436412071',
    projectId: 'ridepair-466010',
    storageBucket: 'ridepair-466010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjPz4ZLOguOGYtsjVH6ufn0zKkdZdn4NA',
    appId: '1:379436412071:ios:5d9e35cb22377d6670ff82',
    messagingSenderId: '379436412071',
    projectId: 'ridepair-466010',
    storageBucket: 'ridepair-466010.firebasestorage.app',
    iosBundleId: 'com.example.ridetogther',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjPz4ZLOguOGYtsjVH6ufn0zKkdZdn4NA',
    appId: '1:379436412071:ios:5d9e35cb22377d6670ff82',
    messagingSenderId: '379436412071',
    projectId: 'ridepair-466010',
    storageBucket: 'ridepair-466010.firebasestorage.app',
    iosBundleId: 'com.example.ridetogther',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGXqqOyNrOpKnegR86hxGZ9AlzqgPUGek',
    appId: '1:379436412071:web:0ed89095a020487570ff82',
    messagingSenderId: '379436412071',
    projectId: 'ridepair-466010',
    authDomain: 'ridepair-466010.firebaseapp.com',
    storageBucket: 'ridepair-466010.firebasestorage.app',
    measurementId: 'G-3F38RQ4V9X',
  );

}